// action types
export const ADD_TF_ITEM = 'ADD_TF_ITEM';
export const SELECT_TF_ITEM = 'SELECT_TF_ITEM';
export const DELETE_TF_ITEM = 'DELETE_TF_ITEM';
export const FETCH_TWEETS_REQUEST = 'FETCH_TWEETS_REQUEST';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_FAILURE = 'FETCH_TWEETS_FAILURE';
export const CHANGE_MODE = 'CHANGE_MODE';
export const FETCH_TWEETS_REINIT = 'FETCH_TWEETS_REINIT';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
